---
title: "Summary of Agustinus’s Gibbs Sampler"
author: "Thomas W. Jones"
date: "7/25/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a summary of a blog post on LDA Gibbs sampling and a quick R implmentation of it. The post and Python code can be found here:  [https://wiseodd.github.io/techblog/2017/09/07/lda-gibbs/](https://wiseodd.github.io/techblog/2017/09/07/lda-gibbs/). I have also saved a PDF copy of the page as I found it on 7/25/2018 in /readings/02_lda/other_ref/. 

# Defining the model

# Implemented code

```{r}
### Declare some toy data ----
# document term matrix of word counts
X <- rbind(c(0, 0, 1, 2, 2),
           c(0, 0, 1, 1, 1),
           c(0, 1, 2, 2, 2),
           c(4, 4, 4, 4, 4),
           c(3, 3, 4, 4, 4),
           c(3, 4, 4, 4, 4))

W <- seq_len(ncol(X))

N_d = nrow(X)  # num of docs
N_w = length(W)  # num of words
N_k = 2  # num of topics

### Initialize parameters ----
set.seed(8675309)

alpha <- rep(1, N_k)
gamma <- rep(1, N_w) # I usually call this "beta"

# Z := word topic assignment, initialized with random integers
# This would have to be a triplet or other sparse matrix
Z <- matrix(sample.int(10, N_w * N_d, replace = TRUE), ncol = N_w, nrow = N_d)

# Pi := document topic distribution
Pi <- gtools::rdirichlet(N_d, alpha)

# B := word topic distribution
B <- gtools::rdirichlet(N_k, gamma)

```

